### ISSUE TITLE
Bug: Can't Connect, error

### ISSUE THREAD

**Issue by Maverynthia** [sg4e/Archipelago#6]
### What happened?

Trying to connect to AP Client after pressing `CONNECT` I get:
```
Now that you are connected, you can use !help to list commands to run via the server. If your client supports it, you may have additional local commands you can list with /help. 
to_bytes() missing required argument 'byteorder (pos 2) 
Traceback (most recent call last): 
File "worlds\bizhawk\context.py", line 263, in main 
File "worlds\bizhawk\context.py", line 201, in _game_watcher 
File "C:\ProgramData\Archipelago\lib\worlds\fm apworld\fm\client.py", line 221, in _game_watcher 
first_bit_field to_bytes(4, "little") + second_bit_field to_bytes(1), 
TypeError: to_bytes() missing required argument 'byteorder' (pos 2) 
```

No items are send and the LUA script now says `Looking for client...' If I don't connect it will say 'Connected' but as soon and I press 'Connect' I get that.
BizHawk is: 2.9.1
AP is 0.4.5

![Screenshot 2024-04-22 004932](https://github.com/sg4e/Archipelago/assets/2293000/4969d6a4-8bb8-4785-80e1-ac13efdfda99)

### What were the expected results?

It connects and sends items like other normal AP games

### Software

While playing

**Comment by sg4e** [comment]
Sorry for the delayed response to this. Thanks for reporting. This will be fixed in the next `apworld` release: 2523db9
